# Part 2. Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices. 

## 1. Example

### 1.1 Load data with pandas

In [1]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [29]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [32]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [31]:
# this is your code to get two vectors
col1 = X[:,0]
col2 = X[:,-2]

print(col1)
print(col2)

[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0 0.0 0.0 0.0 0.0 0.0
 15.0 14.0 0.0 15.0 14.0 24.0 22.0 18.0 21.0 27.0 26.0 25.0 24.0 25.0 26.0
 21.0 10.0 10.0 11.0 9.0 27.0 28.0 25.0 25.0 0.0 19.0 16.0 17.0 19.0 18.0
 14.0 14.0 14.0 14.0 12.0 13.0 13.0 18.0 22.0 19.0 18.0 23.0 28.0 30.0
 30.0 31.0 35.0 27.0 26.0 24.0 25.0 23.0 20.0 21.0 13.0 14.0 15.0 14.0
 17.0 11.0 13.0 12.0 13.0 19.0 15.0 13.0 13.0 14.0 18.0 22.0 21.0 26.0
 22.0 28.0 23.0 28.0 27.0 13.0 14.0 13.0 14.0 15.0 12.0 13.0 13.0 14.0
 13.0 12.0 13.0 18.0 16.0 18.0 18.0 23.0 26.0 11.0 12.0 13.0 12.0 18.0
 20.0 21.0 22.0 18.0 19.0 21.0 26.0 15.0 16.0 29.0 24.0 20.0 19.0 15.0
 24.0 20.0 11.0 20.0 21.0 19.0 15.0 31.0 26.0 32.0 25.0 16.0 16.0 18.0
 16.0 13.0 14.0 14.0 14.0 29.0 26.0 26.0 31.0 32.0 28.0 24.0 26.0 24.0
 26.0 31.0 19.0 18.0 15.0 15.0 16.0 15.0 16.0 14.0 17.0 16.0 15.0 18.0
 21.0 20.0 13.0 29.0 23.0 20.0 23.0 24.0 25.0 24.0 18.0 29.0 19.0 23.0
 23.0 22.0 25.0 33.0 28.0 25.0 25.0 26.0 27.0 17.5 16.0 15.5 14.5 22.0

### 2.2 Perform following operations on these two vectors and print the result

In [41]:

# 1. addition and subtraction
col_add = col1 + col2
col_sub = col1 - col2

print(col_add)
print(col_sub)

# 2. element-wise multiplication
col_mul = np.multiply(col1,col2)
print(col_mul)

# 3. inner product
inner_pro = np.inner(col1,col2)
print(inner_pro)

# 4. three norms
norm1 = np.linalg.norm(col1,1)
norm2 = np.linalg.norm(col1,2)
norm_inf = np.linalg.norm(col1,np.inf)

print(norm1)
print(norm2)
print(norm_inf)

# 5. compute the distance between these two vectors
dist = np.linalg.norm(col_sub, 2)
print(dist)

9358.800000000003
494.28813459357895
46.6
216.10913909411607


### 2.3 Get the first three columns and the last three columns from X

In [43]:
# this is your code to get two matrices: A, B
A = X[:,0:3]
B = X[:,-3:]

print(A)
print(B)

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 ...
 [32.0 4 135.0]
 [28.0 4 120.0]
 [31.0 4 119.0]]
[[3504 12.0 70]
 [3693 11.5 70]
 [3436 11.0 70]
 ...
 [2295 11.6 82]
 [2625 18.6 82]
 [2720 19.4 82]]


### 2.4 Perform following operations on these two matrices and print the result

In [55]:
# 1. addition and subtraction 
print(A+B)
print(A-B)

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = np.transpose(B)
print(C.shape)

# 3. compute the product between A and C, and print the result and its shape
AC = np.dot(A,C)
print(AC)
print(AC.shape)

# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = np.transpose(A)
print(D.shape)

# 5. compute the product between D and B, and print the result and its shape
DB = np.dot(D,B)
print(DB)
print(DB.shape)

(3, 406)
[[84658.0 88056.0 83426.0 ... 66576.8 72572.8 74289.2]
 [77156.0 79987.0 76128.0 ... 63217.8 68223.8 69655.2]
 [85428.0 88826.0 84196.0 ... 67478.8 73474.8 75191.2]
 ...
 [121626.0 127672.0 119446.0 ... 84556.4 95144.4 98187.6]
 [106560.0 111850.0 104652.0 ... 74146.4 83414.4 86077.6]
 [117002.0 122859.0 114890.0 ... 80949.4 91207.4 94155.6]]
(406, 406)
(3, 406)
[[25614040.900000002 149295.04000000004 718009.0999999995]
 [7149030 33484.69999999997 167835]
 [269175402.0 1160836.2999999998 5943079.0]]
(3, 3)
